# -*- coding: utf-8 -*-
{
    'name': "cantiericasa_base",
    'version': "1.0",
    'author': 'Abstract',
    'website': 'http://www.cantiericasa.it/',
    'category': '',
    'description': """Base modules for Cantiericasa.""",
    'license': 'AGPL-3',
    'depends': [
        'account',
        'account_accountant',
        'account_cancel',
        'account_invoice_force_number',
        'account_voucher',
        'analytic',
        'base_iban',
        'base_vat',
        'calendar',
        'cantieri_casa_accounts_chart',
        'crm',
        'disable_openerp_online',
        'document',
        'hr',
        'l10n_it_fiscalcode',
        'l10n_it_base_location_geonames_import',
        'l10n_it_ddt',
        'mass_editing',
        'mrp',
        'mrp_operations',
        'project',
        'purchase',
        'sale',
        'sale_crm',
        'sale_mrp',
        'sale_stock',
        'stock',
    ],
    'data': [
        'data/odoo_reset.xml',
        'data/res_company.xml',
        'data/decimal_precision.xml',
    ],
    'update_xml': [
    ],
    'test': [
    ],
    'active': False,
    'installable': True
}
